bug fix: "Active" button not getting focused state
react95-io/React95 pull request #384
Opened 2023-04-09 02:46 UTC by afzalzbr

The `focusOutline` was not including any case for active === true.

I've made changes in the file: `src\Button\Button.tsx`:
![image](https://user-images.githubusercontent.com/49808043/230751214-4c4bb5e6-7284-4563-aabc-6a9c24f7aec4.png)

Following is the working example of the fix for the 'Active' button, followed by a picture showing no other buttons' styles are being compromised:
![image](https://user-images.githubusercontent.com/49808043/230751259-83238241-9786-4669-b4f6-23327495f802.png)

![image](https://user-images.githubusercontent.com/49808043/230751296-63440370-85d7-429c-84b4-4c110eddb07b.png)

I hope this helps!

2023-04-13 07:32 UTC, arturbien commented
@afzalzbr there are some linting issues in CI

2023-04-13 07:39 UTC, afzalzbr commented
@arturbien okay I'll check.

2023-04-13 08:31 UTC, afzalzbr commented
@arturbien fixed the linting issue, please review and approve.

2023-04-20 09:31 UTC, arturbien requested changes
Seems like we can make this PR a lot simpler.

Just remove the `!active` flag on line 167 instead of adding the code you've added. I think the result will be the same right?

https://github.com/react95-io/React95/pull/384/files#diff-27a5747646c8932c6f4df16f6a7882c2f7a9481111c57cb83944df1c58b3c7bdR167

2023-04-21 09:49 UTC, arturbien approved these changes

2023-04-21 09:56 UTC, arturbien commented
@afzalzbr great! Now before I merge please squash all the commits into single commit with message:

`fix(Button): active button focus outline`

2023-04-24 01:31 UTC, afzalzbr commented
@arturbien done

2023-04-24 16:20 UTC, merged

2023-04-24 16:21 UTC, arturbien commented
@afzalzbr your commit was merged to master. Thank you for the contribution <3